Repository nextcloud/integration_openai, pull requests merged in 2024-03, with the labels that each got.

#81 Maintenance: update dependencies and enable psalm and php cs check
  .github/workflows/lint-php-cs.yml
  .github/workflows/psalm.yml
  CHANGELOG.md
  composer.json
  composer.lock
  lib/Controller/OpenAiAPIController.php
  lib/Db/ImageGenerationMapper.php
  lib/Db/ImageUrlMapper.php
  lib/Db/PromptMapper.php
  lib/Db/QuotaUsageMapper.php
  lib/Listener/OpenAiReferenceListener.php
  lib/Reference/ChatGptReferenceProvider.php
  lib/Reference/ImageReferenceProvider.php
  lib/Reference/WhisperReferenceProvider.php
  lib/Service/OpenAiAPIService.php
  lib/Service/OpenAiSettingsService.php
  lib/Settings/AdminSection.php
  lib/Settings/PersonalSection.php
  lib/TextProcessing/FreePromptProvider.php
  lib/TextProcessing/HeadlineProvider.php
  lib/TextProcessing/ReformulateProvider.php
  lib/TextProcessing/SummaryProvider.php
  package-lock.json
  package.json
  psalm.xml
  src/views/ChatGptCustomPickerElement.vue
  src/views/ImageCustomPickerElement.vue
  vendor-bin/php-cs-fixer/composer.json
  vendor-bin/php-cs-fixer/composer.lock
  vendor-bin/phpunit/composer.json
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm-phar/composer.json
  vendor-bin/psalm-phar/composer.lock
Labels: feedback-requested

#82 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
Labels: automated, dependencies, 3. to review

#84 Fix: use basic auth to get generated images if necessary
  lib/AppInfo/Application.php
  lib/Controller/OpenAiAPIController.php
  lib/Service/OpenAiAPIService.php
  lib/TextProcessing/FreePromptProvider.php
  lib/TextToImage/TextToImageProvider.php
  tests/unit/Controller/OpenAiControllerTest.php
  tests/unit/Providers/OpenAiProviderTest.php
Labels: bug
