Repository nextcloud/integration_openai, pull requests merged in 2025-01, with the labels that each got.

#169 Feat: add proofread provider
  lib/AppInfo/Application.php
  lib/TaskProcessing/ProofreadProvider.php
  tests/unit/Providers/OpenAiProviderTest.php
Labels: feedback-requested

#176 Use max_completion_tokens instead of deprecated max_tokens
  composer.lock
  lib/Service/OpenAiAPIService.php
  lib/Service/OpenAiSettingsService.php
  src/components/AdminSettings.vue
  tests/unit/Providers/OpenAiProviderTest.php
  vendor-bin/php-cs-fixer/composer.lock
  vendor-bin/phpunit/composer.lock
Labels: enhancement, 3. to review

#178 Mention IONOS as service with an OpenAI-compatible API
  README.md
  appinfo/info.xml
  src/components/AdminSettings.vue
Labels: documentation, enhancement, 3. to review

#179 Support chatting with o1 models
  lib/Service/OpenAiAPIService.php
Labels: enhancement, 3. to review

#185 Add a warning if the assistant app is not installed
  lib/Settings/Admin.php
  src/components/AdminSettings.vue
Labels: enhancement, 3. to review
